-- ============================================
-- Seed existing projects into Supabase
-- Run AFTER 001_projects_table.sql
-- ============================================

INSERT INTO public.projects (project_slug, status, category, featured, year, title_cs, title_en, summary_cs, summary_en, body_cs, body_en, stack, links_website, links_demo, links_github, links_other, links_other_label, images)
VALUES

-- FACHA
(
  'facha',
  'beta',
  'app',
  true,
  2025,
  'FACHA',
  'FACHA',
  'Offline fakturační a evidenční aplikace pro řemeslníky a OSVČ. Generuje PDF faktury s QR platbami, funguje bez internetu.',
  'Offline invoice and job tracking app for tradespeople and freelancers. Generates PDF invoices with QR payments, works without internet.',
  E'## O projektu\n\nFACHA je mobilní aplikace pro české řemeslníky a OSVČ — digitální parťák pro správu zakázek, fotodokumentaci a fakturaci. Celá aplikace funguje offline-first, takže ji můžete používat i na stavbě bez signálu.\n\n### Problém\n\nŘemeslníci a OSVČ tráví hodiny papírováním. Ztrácejí přehled o zakázkách, zapomínají detaily, fakturují pozdě nebo vůbec. Většina fakturačních aplikací vyžaduje internet, je složitá a není navržená pro práci v terénu.\n\n### Řešení\n\nFACHA je jednoduchá offline aplikace, ve které za pár kliknutí:\n\n- Založíte zakázku a přiřadíte klienta\n- Vyfotíte stav „před" a „po"\n- Zapíšete si poznámky přímo na místě\n- Vygenerujete PDF fakturu s QR kódem pro platbu\n- Sdílíte fakturu přes WhatsApp, email nebo jinak\n\n### Klíčové funkce\n\n- **Kompletní offline funkcionalita** — lokální SQLite databáze (Drift), žádný cloud\n- **Správa zakázek** — stavy: návrh → naplánováno → probíhá → hotovo → fakturováno\n- **Evidence klientů** — ruční zadání nebo automatické načtení z ARES (stačí zadat IČO)\n- **Fotodokumentace** — foto před/po přímo z aplikace\n- **PDF fakturace** — generování faktur s vlastním brandingem a kontaktními údaji\n- **QR platby** — český SPD standard pro okamžité bankovní platby\n- **Navigace a volání** — navigace na adresu zakázky, rychlé volání klientovi\n- **Sdílení** — export PDF přes systémové sdílení (WhatsApp, email, Messenger...)\n\n### Tech stack\n\nFlutter + Riverpod (state management), go_router (navigace), Drift/SQLite (offline databáze), Dio (HTTP/ARES), pdf + printing (PDF generování), qr (QR kódy).\n\nAplikace je v beta verzi a aktivně vyvíjena na základě zpětné vazby uživatelů.',
  E'## About the Project\n\nFACHA is a mobile app for Czech tradespeople and freelancers — a digital sidekick for job management, photo documentation, and invoicing. The entire app works offline-first, so you can use it on a construction site with no signal.\n\n### Problem\n\nTradespeople and freelancers spend hours on paperwork. They lose track of jobs, forget details, and invoice late or not at all. Most invoicing apps require internet, are complex, and aren''t designed for fieldwork.\n\n### Solution\n\nFACHA is a simple offline app where in just a few taps you can:\n\n- Create a job and assign a client\n- Take "before" and "after" photos\n- Write notes directly on site\n- Generate a PDF invoice with QR code for payment\n- Share the invoice via WhatsApp, email, or other apps\n\n### Key Features\n\n- **Complete offline functionality** — local SQLite database (Drift), no cloud required\n- **Job management** — states: draft → scheduled → in progress → done → invoiced\n- **Client records** — manual entry or automatic lookup from ARES (Czech business registry, just enter company ID)\n- **Photo documentation** — before/after photos directly from the app\n- **PDF invoicing** — invoice generation with custom branding and contact details\n- **QR payments** — Czech SPD standard for instant bank transfers\n- **Navigation & calling** — navigate to job address, quick-call the client\n- **Sharing** — export PDF via system share sheet (WhatsApp, email, Messenger...)\n\n### Tech Stack\n\nFlutter + Riverpod (state management), go_router (navigation), Drift/SQLite (offline database), Dio (HTTP/ARES), pdf + printing (PDF generation), qr (QR codes).\n\nThe app is in beta and actively developed based on user feedback.',
  ARRAY['Flutter', 'Riverpod', 'Drift/SQLite', 'PDF', 'QR', 'ARES API'],
  '',
  'https://www.dropbox.com/scl/fi/q4oqquu4rtfrrbd2loret/FACHA-v0.3.0.apk?rlkey=wsyz50qzmvcr7aoagfe6zjhvx&st=s1496trc&dl=0',
  '',
  'https://docs.google.com/forms/d/13UHdx3Sa2nBoMW9gzbulC2n7O-hdm-yDt5XSC1cY__k/edit?usp=forms_home&ouid=101289173675479405977',
  'Feedback formulář',
  ARRAY['/uploads/screenshot_20260205-014402.jpg','/uploads/screenshot_20260205-014357.jpg','/uploads/screenshot_20260205-014221.jpg','/uploads/screenshot_20260205-014345.jpg','/uploads/screenshot_20260205-014144.jpg','/uploads/screenshot_20260205-014051.jpg','/uploads/screenshot_20260205-014302.jpg','/uploads/screenshot_20260205-014136.jpg','/uploads/screenshot_20260205-014031.jpg','/uploads/screenshot_20260204-151230.jpg','/uploads/screenshot_20260205-014028.jpg','/uploads/screenshot_20260205-014307.jpg','/uploads/screenshot_20260205-014154.jpg','/uploads/screenshot_20260205-014042.jpg','/uploads/screenshot_20260205-014108.jpg','/uploads/screenshot_20260205-014037.jpg']
),

-- AI Audit Tool
(
  'ai-audit-tool',
  'beta',
  'tool',
  true,
  2026,
  'AI Audit Tool',
  'AI Audit Tool',
  'Desktopový nástroj pro audit AI-připravenosti webů. Skenuje stránky, hodnotí 6 pilířů (indexability, schema, DOM sémantika, obsah, média, provozní signály) a generuje PDF report s konkrétními doporučeními.',
  'Desktop tool for auditing website AI-readiness. Scans pages, evaluates 6 pillars (indexability, schema, DOM semantics, content, media, operational signals) and generates PDF reports with actionable recommendations.',
  E'## O projektu\n\nAI Audit Tool (GEO Auditor) je desktopová aplikace pro SEO/GEO konzultanty a webmastery, která analyzuje, jak dobře jsou webové stránky připraveny na éru AI vyhledávačů — ChatGPT, Perplexity, Google SGE a další AI asistenty.\n\n### Problém\n\nAI asistenti a vyhledávače potřebují strukturovaná, sémanticky čistá data, aby dokázali správně extrahovat informace o produktech, službách a firmách. Většina webů nemá správné Schema.org značky, chybí jim strukturovaný obsah a AI systémy z nich nedokáží spolehlivě vytáhnout klíčová fakta.\n\n### Řešení\n\nAI Audit Tool provede hloubkovou analýzu celého webu a vyhodnotí jeho AI-připravenost na základě 6 pilířů:\n\n1. **Indexability & Access** — robots.txt, meta direktivy, canonical URL, HTTP status\n2. **Structured Data Coverage** — Schema.org typy a jejich kompletnost\n3. **Extractability & DOM Semantics** — H1/H2 struktura, sémantický obsah, DOM kvalita\n4. **Content Completeness** — poměr faktů vs. fluff, přítomnost kritických polí\n5. **Media & Alt Context** — ALT texty obrázků, kvalita a velikost médií\n6. **Operational Signals** — sitemap, breadcrumbs, interní prolinkování\n\n### Klíčové funkce\n\n- **Dva režimy** — ⚡ Quick Snapshot (bez AI, rychlý přehled) a 🤖 AI Enhanced (s Gemini, hloubková analýza)\n- **Template clustering** — dvou-fázová pipeline, která seskupí podobné stránky a analyzuje jen reprezentanty (šetří čas a API volání)\n- **Agent Extraction Test** — deterministický test, zda AI dokáže z webu extrahovat klíčová fakta\n- **Checkpoint systém** — audit lze kdykoli zastavit a pokračovat později\n- **PDF reporty** — profesionální PDF s vizualizacemi, skóre a konkrétními doporučeními\n- **Implementation Checklist** — Excel export s prioritizovanými úkoly (P0/P1/P2) pro vývojáře\n- **Email outreach** — integrovaný modul pro oslovení potenciálních klientů\n- **ARES integrace** — ověření firem z českého obchodního rejstříku\n- **Licenční systém** — Lemon Squeezy integrace (Standard/Recommended/PRO plány)\n\n### Tech stack\n\nPython + Streamlit (UI), Playwright (JS rendering), BeautifulSoup + lxml (parsing), Google Gemini (AI analýza), FPDF2 (PDF generování), Plotly (vizualizace), SQLite (historie auditů).',
  E'## About the Project\n\nAI Audit Tool (GEO Auditor) is a desktop application for SEO/GEO consultants and webmasters that analyzes how well websites are prepared for the era of AI search engines — ChatGPT, Perplexity, Google SGE, and other AI assistants.\n\n### Problem\n\nAI assistants and search engines need structured, semantically clean data to reliably extract information about products, services, and companies. Most websites lack proper Schema.org markup, have unstructured content, and AI systems cannot reliably extract key facts from them.\n\n### Solution\n\nAI Audit Tool performs a deep analysis of entire websites and evaluates their AI-readiness based on 6 pillars:\n\n1. **Indexability & Access** — robots.txt, meta directives, canonical URLs, HTTP status\n2. **Structured Data Coverage** — Schema.org types and their completeness\n3. **Extractability & DOM Semantics** — H1/H2 structure, semantic content, DOM quality\n4. **Content Completeness** — facts vs. fluff ratio, presence of critical fields\n5. **Media & Alt Context** — image ALT texts, media quality and size\n6. **Operational Signals** — sitemap, breadcrumbs, internal linking\n\n### Key Features\n\n- **Two modes** — ⚡ Quick Snapshot (no AI, fast overview) and 🤖 AI Enhanced (with Gemini, deep analysis)\n- **Template clustering** — two-phase pipeline that groups similar pages and analyzes only representatives (saves time and API calls)\n- **Agent Extraction Test** — deterministic test of whether AI can extract key facts from the site\n- **Checkpoint system** — audit can be stopped and resumed at any time\n- **PDF reports** — professional PDFs with visualizations, scores, and actionable recommendations\n- **Implementation Checklist** — Excel export with prioritized tasks (P0/P1/P2) for developers\n- **Email outreach** — integrated module for cold outreach to potential clients\n- **ARES integration** — company verification from Czech business registry\n- **Licensing system** — Lemon Squeezy integration (Standard/Recommended/PRO plans)\n\n### Tech Stack\n\nPython + Streamlit (UI), Playwright (JS rendering), BeautifulSoup + lxml (parsing), Google Gemini (AI analysis), FPDF2 (PDF generation), Plotly (visualization), SQLite (audit history).',
  ARRAY['Python', 'Streamlit', 'Playwright', 'Gemini AI', 'PDF'],
  '', '', '', '', '',
  ARRAY[]::TEXT[]
),

-- Game System Simulator (GSS)
(
  'idle-economy-sim',
  'live',
  'tool',
  true,
  2025,
  'Game System Simulator (GSS)',
  'Game System Simulator (GSS)',
  'Webový nástroj pro indie game devs — vizuálně navrhni, simuluj a vybalancuj herní ekonomiku (idle/incremental). Definuj resources, producery, upgrady a sleduj grafy produkce v čase. Export do JSON/CSV.',
  'Web-based tool for indie game devs — visually design, simulate, and balance game economies (idle/incremental). Define resources, producers, upgrades and watch production graphs over time. Export to JSON/CSV.',
  E'## O projektu\n\nGame System Simulator (GSS) je webový nástroj pro indie herní vývojáře, kteří potřebují navrhnout a vybalancovat ekonomické a progression systémy pro idle/tycoon/incremental hry — bez toho, aby museli psát kód.\n\n### Problém\n\nIdle hry často trpí špatně vyváženou ekonomikou: hráč buď uvízne na jednom místě, nebo naopak dokončí hru příliš rychle. Balancování ekonomiky je iterativní proces, který vyžaduje opakované testování — a bez dedikovaného nástroje to znamená hodiny úprav přímo v kódu hry.\n\n### Řešení\n\nGSS poskytuje vizuální rozhraní, kde si nadefinujete celou herní ekonomiku a v reálném čase sledujete, jak se chová v simulaci. Žádný kód, jen konfigurujte a testujte.\n\n### Jak to funguje\n\n1. **Definujte resources** — základní měny a materiály (coins, gems, wood...)\n2. **Vytvořte producery** — budovy/generátory s produkční sazbou, cenou a scaling formulí (lineární/exponenciální)\n3. **Přidejte upgrady** — multiplikátory produkce, odemykací podmínky (úroveň produceru, množství resources, čas)\n4. **Nastavte počáteční stav** — výchozí množství resources\n5. **Spusťte simulaci** — testujte ekonomiku na různých časových úsecích (1 hodina, 24 hodin, 7 dní)\n6. **Analyzujte grafy** — Money vs Time a Production Rate vizualizace pro balancovací rozhodnutí\n7. **Exportujte** — konfigurace jako JSON pro import do hry, simulační výsledky jako CSV\n\n### Tech stack\n\nTypeScript pro typově bezpečný vývoj, Chart.js pro vizualizaci dat, Webpack pro bundling. Obsahuje i Godot SDK a Unity SDK pro přímou integraci do herních enginů.\n\nNástroj je dostupný na itch.io a aktivně vyvíjen.',
  E'## About the Project\n\nGame System Simulator (GSS) is a web-based tool for indie game developers who need to design and balance economic and progression systems for idle/tycoon/incremental games — without writing code.\n\n### Problem\n\nIdle games often suffer from poorly balanced economies: players either get stuck or finish the game too quickly. Balancing an economy is an iterative process requiring repeated testing — and without a dedicated tool, this means hours of tweaking directly in game code.\n\n### Solution\n\nGSS provides a visual interface where you define your entire game economy and watch it behave in real-time simulation. No code, just configure and test.\n\n### How It Works\n\n1. **Define resources** — basic currencies and materials (coins, gems, wood...)\n2. **Create producers** — buildings/generators with production rate, cost, and scaling formula (linear/exponential)\n3. **Add upgrades** — production multipliers, unlock conditions (producer level, resource amount, time)\n4. **Set starting state** — initial resource amounts\n5. **Run simulation** — test your economy over different time periods (1 hour, 24 hours, 7 days)\n6. **Analyze graphs** — Money vs Time and Production Rate visualizations for balancing decisions\n7. **Export** — configurations as JSON for game import, simulation results as CSV\n\n### Tech Stack\n\nTypeScript for type-safe development, Chart.js for data visualization, Webpack for bundling. Includes Godot SDK and Unity SDK for direct game engine integration.\n\nThe tool is available on itch.io and actively developed.',
  ARRAY['TypeScript', 'Chart.js', 'Webpack', 'Godot SDK'],
  'https://neopryus.itch.io/idle-economy-simulator',
  '', '', '', '',
  ARRAY['/uploads/idle-economy-sim-screenshot-1.png']
),

-- SpotMe
(
  'spotme',
  'prototype',
  'app',
  false,
  2026,
  'SpotMe',
  'SpotMe',
  'Android appka pro rychlé nalezení parťáka na trénink ve stejné posilovně a čase. Žádný feed, žádné profily — čistě utilita na domluvu společného cvičení.',
  'Android app for quickly finding a gym partner at the same gym and time. No feed, no profiles — purely a utility for arranging joint workouts.',
  E'## O projektu\n\nSpotMe je Android aplikace pro lidi, kteří cvičí sami a chtějí občas parťáka na trénink — ať už začátečníky nebo pokročilé. Žádný sociální feed, žádné zbytečné profily. Čistě utilita na domluvu.\n\n### Problém\n\nHodně lidí by cvičilo pravidelněji, kdyby měli parťáka. Přes sociální sítě je domlouvání pomalé a nekomfortní. Hlavní problém je najít někoho ve stejném čase a místě.\n\n### Řešení\n\nSpotMe funguje jednoduše:\n\n1. Vyberete si město a posilovnu\n2. Nastavíte časové okno (např. dnes 18–20)\n3. Vytvoříte příspěvek „jdu cvičit" s typem tréninku (nohy, záda, kardio...)\n4. Systém vás automaticky propojí s lidmi ve stejné posilovně a překrývajícím se čase\n5. Po matchi se otevře jednoduchý chat\n\n### Klíčové funkce\n\n- **Výběr posilovny** — město, gym, adresa s mapou\n- **Časové okno** — nastavení kdy plánujete cvičit\n- **Příspěvek „jdu cvičit"** — typ tréninku, úroveň, poznámka (vytvoření za 60 sekund)\n- **Automatický match** — stejné místo + překryv času\n- **Chat** — jednoduchá komunikace pouze po oboustranném matchi\n- **Bezpečnost** — žádné pravé jméno, minimální osobní údaje, blokování a reporting uživatelů\n- **Automatické mazání** — zprávy se smažou 24h po tréninku, data po 30 dnech neaktivity\n\n### Premium (99 Kč/měsíc)\n\n- Neomezené příspěvky (free = 1/den)\n- Pokročilé filtry\n- Zvýraznění příspěvku\n- Verified badge\n\n### Tech stack\n\nKotlin + Jetpack Compose (UI), Firebase Auth + Firestore + Cloud Messaging (backend), Hilt (dependency injection), MVVM architektura. Lokalizace CZ/EN.\n\nAplikace je ve fázi prototypu.',
  E'## About the Project\n\nSpotMe is an Android app for people who work out alone and want an occasional training partner — whether beginners or advanced. No social feed, no unnecessary profiles. Purely a utility for arranging workouts.\n\n### Problem\n\nMany people would exercise more regularly if they had a partner. Arranging through social media is slow and uncomfortable. The main challenge is finding someone at the same time and place.\n\n### Solution\n\nSpotMe works simply:\n\n1. Select your city and gym\n2. Set a time window (e.g., today 6–8 PM)\n3. Create a "going to work out" post with workout type (legs, back, cardio...)\n4. The system automatically matches you with people at the same gym with overlapping time\n5. After matching, a simple chat opens\n\n### Key Features\n\n- **Gym selection** — city, gym, address with map\n- **Time window** — set when you plan to work out\n- **"Going to work out" post** — workout type, level, note (creation in 60 seconds)\n- **Automatic matching** — same location + time overlap\n- **Chat** — simple communication only after mutual match\n- **Safety** — no real name required, minimal personal data, user blocking and reporting\n- **Auto-deletion** — messages deleted 24h after workout, data after 30 days of inactivity\n\n### Premium (99 CZK/month)\n\n- Unlimited posts (free = 1/day)\n- Advanced filters\n- Highlighted posts\n- Verified badge\n\n### Tech Stack\n\nKotlin + Jetpack Compose (UI), Firebase Auth + Firestore + Cloud Messaging (backend), Hilt (dependency injection), MVVM architecture. Localization CZ/EN.\n\nThe app is in prototype stage.',
  ARRAY['Kotlin', 'Jetpack Compose', 'Firebase', 'Hilt'],
  '', '', '', '', '',
  ARRAY[]::TEXT[]
),

-- Web Firewall
(
  'web-firewall',
  'prototype',
  'tool',
  true,
  2026,
  'Web Firewall',
  'Web Firewall',
  'Chrome extension pro bezpečnější prohlížení — skrývá low-quality obsah, detekuje scam/dark pattern UI a varuje před prompt injection útoky cílícími na AI agenty. Vše běží lokálně v prohlížeči.',
  'Privacy-first Chrome extension for safer browsing — hides low-quality content, detects scam/dark pattern UI, and warns about prompt injection attacks targeting AI agents. Runs entirely locally.',
  E'## O projektu\n\nWeb Firewall je Chrome extension (Manifest V3), která poskytuje tři vrstvy ochrany při prohlížení webu. Vše běží lokálně — žádná data stránek se neodesílají na servery.\n\n### Problém\n\nModerní webové stránky jsou plné skrytých manipulativních prvků: falešná tlačítka ke stažení, agresivní overlay reklamy, dark patterns a dokonce prompt injection útoky cílící na AI agenty a scrapery. Běžný uživatel tyto hrozby nevidí.\n\n### 3 ochranné vrstvy\n\n- **Quality Shield (Noise Canceling)** — automaticky identifikuje a skrývá low-value bloky: „related articles", agresivní CTA, boilerplate. Zachovává hlavní obsah a navigaci.\n- **Scam Shield** — detekuje falešná download tlačítka, dark pattern overlaye, interstitialy a clickfix patterny (PowerShell/terminal bait). Volitelná click-guard ochrana rizikových elementů.\n- **Injection Shield** — odhaluje skrytý text cílící na AI agenty/scrapery, prompt injection fráze, „agent bait" (požadavky na tokeny, klíče, clipboard) a podezřelý obsah v aria-label/alt/title/meta atributech.\n\n### Režimy\n\n- **Off** — extension vypnuta pro daný web\n- **Clean** — lehké filtrování, zachovává většinu obsahu\n- **Focus** — střední filtrování, skrývá sidebary a rušivé prvky\n- **Strict** — agresivní filtrování, click-guard na rizikových elementech\n\n### Principy návrhu\n\n- **Local-first** — veškerá analýza probíhá v content scriptech, žádné serverové volání (Free mode)\n- **Bezpečný** — minimální oprávnění, žádný eval, žádný remote kód\n- **Rychlý** — neblokující, inkrementální analýza s debounced observery (< 150ms CPU)\n- **Reverzibilní** — uživatel může kdykoli obnovit skrytý obsah\n- **Vysvětlitelný** — každé rozhodnutí obsahuje důvod a skóre\n\nExtension je ve fázi prototypu, připravuje se vydání na Chrome Web Store.',
  E'## About the Project\n\nWeb Firewall is a Chrome extension (Manifest V3) that provides three layers of protection while browsing. Everything runs locally — no page content is ever sent to external servers.\n\n### Problem\n\nModern websites are full of hidden manipulative elements: fake download buttons, aggressive overlay ads, dark patterns, and even prompt injection attacks targeting AI agents and scrapers. Regular users can''t see these threats.\n\n### 3 Protection Layers\n\n- **Quality Shield (Noise Canceling)** — automatically identifies and hides low-value content blocks: "related articles", aggressive CTAs, boilerplate. Preserves main content and navigation.\n- **Scam Shield** — detects fake download buttons, dark pattern overlays, interstitials, and clickfix patterns (PowerShell/terminal bait). Optional click-guard for high-risk elements.\n- **Injection Shield** — detects hidden text targeting AI agents/scrapers, prompt injection phrases, "agent bait" (requests for tokens, keys, clipboard access), and suspicious content in aria-label/alt/title/meta attributes.\n\n### Modes\n\n- **Off** — extension disabled for this site\n- **Clean** — light filtering, preserves most content\n- **Focus** — moderate filtering, hides sidebars and distractions\n- **Strict** — aggressive filtering, click-guards on risky elements\n\n### Design Principles\n\n- **Local-first** — all analysis runs in content scripts, no server calls (Free mode)\n- **Safe by design** — minimal permissions, no eval, no remote code\n- **Fast** — non-blocking, incremental analysis with debounced observers (< 150ms CPU)\n- **Reversible** — user can restore any hidden content\n- **Explainable** — all decisions include reasons and scores\n\nThe extension is in prototype stage, preparing for Chrome Web Store release.',
  ARRAY['Chrome Extension', 'Manifest V3', 'JavaScript', 'Content Scripts'],
  '', '', '', '', '',
  ARRAY['/uploads/web-firewall-screenshot-1.png']
)

ON CONFLICT (project_slug) DO NOTHING;
